---
apiVersion: "route.openshift.io/v1"
kind: "Route"
metadata:
  labels:
    app.kubernetes.io/name: "el-quarkus-demo"
    app.kubernetes.io/part-of: Triggers
  name: "el-quarkus-demo"
spec:
  port:
    targetPort: http-listener
  tls:
    termination: edge
  to:
    kind: "Service"
    name: "el-quarkus-demo"
