---
apiVersion: operators.coreos.com/v1alpha2
kind: OperatorGroup
metadata:
  name: infinispan-operator-group
  namespace: datagrid
spec:
  targetNamespaces:
  - datagrid
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: infinispan
  namespace: datagrid
spec:
  channel: 2.0.x
  installPlanApproval: Automatic
  name: infinispan
  source: community-operators
  sourceNamespace: openshift-marketplace
#  startingCSV: infinispan-operator.v2.0.0.Final
